Reto 2/ambientalAnalysis/ambientalAnalysis/urls.py
from django.contrib import admin
from django.urls import path, include
from analiticas import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls, namespace='analiticas')),
]

Reto 2/ambientalAnalysis/analiticas/urls.py
from django.urls import include, path
from .views import conexion, prueba, home, analitica1, analitica2, analitica3, analitica4

app_name='analiticas'

urlpatterns = [
    #path("pruebas/", .as_view(), name=""),
    path("", home, name="home"),
    path("prueba/", prueba, name='prueba'),
    path('analitica1/', analitica1, name='analitica1'),
    path('analitica2/', analitica2, name='analitica2'),
    path('analitica3/', analitica3, name='analitica3'),
    path('analitica4/', analitica4, name='analitica4'),
]

Reto 2/ambientalAnalysis/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    {% block styles %}

    {% endblock styles %}

    <title>Analiticas ambientales</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success position-sticky mb-5">
            <a class="navbar-brand" href="#">Analiticas Ambientales</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'analiticas:home' %}">Inicio</a>
                    <a class="nav-item nav-link" href="{% url 'analiticas:analitica1' %}">Menciones</a>
                    <a class="nav-item nav-link" href="{% url 'analiticas:analitica2' %}">Palabras clave individual</a>
                    <a class="nav-item nav-link" href="{% url 'analiticas:analitica3' %}"">Palabras clave conjunto</a>
                    <a class="nav-item nav-link" href="{% url 'analiticas:analitica4' %}"">Palabras clave Candidatos</a>
                </div>
            </div>
        </nav>
    </header>

    {% block content %}

    {% endblock content %}

    <footer class="mt-5">
        <div class="container-fluid">
            <div class="row bg-success py-3">
                <div class="col-12 col-md-6">
                    <h3 class="text-white">Introduccion a la ciencia de datos</h3>
                    <h4 class="text-white">Presentado por:</h4>
                    <p class="text-white">
                        David Alejandro Aparicio Grandas - 20151020060 
                        <br> 
                        Norbey Danilo Muñoz - 20151020050
                    </p>
                </div>
                <div class="col-12 col-md-6 text-center">
                    <img src="{% static 'img/logo.jpg' %}" class="img-fluid logo rounded">
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>